// eslint-disable-next-line import/prefer-default-export
export const GET_ARTICLES = 'GET_ARTICLES';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const SUCCESS_TOAST = 'SUCCESS_TOAST';
export const FAILURE_TOAST = 'FAILURE_TOAST';
export const SET_ARTICLE = 'SET_ARTICLE';
export const SET_ARTICLE_ERROR = 'SET_ARTICLE_ERROR';
export const GET_RECOMMENDED_ARTICLES = 'GET_RECOMMENDED_ARTICLES';
export const GET_LATEST_ARTICLES = 'GET_LATEST_ARTICLES';
export const GET_TRENDING_ARTICLES = 'GET_TRENDING_ARTICLES';
export const CURRENT_USER = 'CURRENT_USER';
export const GET_RESET_KEY = 'GET_RESET_KEY';
export const SEND_NEW_PASSWORD = 'SEND_NEW_PASSWORD';
